apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: revhive

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: YOUR_DOCKER_USERNAME/revhive-frontend:latest

          ports:
            - containerPort: 3000

          imagePullPolicy: Always
